  <div class="mid">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi3?> >
          <?php if(count($catalogueParent)>0):?>
            <?php if ($curLang === 'tc'): ?>
              <?php echo $catalogueParent->name_tc; ?>
            <?php else: ?>
              <?php echo $catalogueParent->name_en; ?>
            <?php endif; ?>
        <?php endif;?>
        </span>
      </div>
    </div>
    <div class="wrap">
      <div class="menu2">

        <?php if ($curLang === 'tc'): ?>
          <?php foreach ($categorylist as $category): ?>
            <div class="nav" data-aid="<?php echo $category['id']?>">
              <div class="tit">
                <?php echo $category['name_tc']?>
              </div>
              <?php if(isset($category['sub_nav'])): ?>
                <?php foreach ($category['sub_nav'] as $subnav): ?>
                  <div class="sub-navi">
                    <a href="<?=$home?>catalogue?cid=<?php echo $subnav['id']?>" class="sub-tit" data-cid="<?php echo $subnav['id']?>">
                      <?php echo $subnav['name_tc']?>
                    </a>
                  </div>
                <?php endforeach; ?>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        <?php else: ?>
          <?php foreach ($categorylist as $category): ?>
            <div class="nav" data-aid="<?php echo $category['id']?>">
              <div class="tit">
                <?php echo $category['name_en']?>
              </div>
              <?php if(isset($category['sub_nav'])): ?>
                <?php foreach ($category['sub_nav'] as $subnav): ?>
                  <div class="sub-navi">
                    <a href="<?=$home?>catalogue?cid=<?php echo $subnav['id']?>" class="sub-tit" data-cid="<?php echo $subnav['id']?>">
                      <?php echo $subnav['name_en']?>
                    </a>
                  </div>
                <?php endforeach; ?>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>
        <?php endif; ?>
<!--
        <div class="nav">
          <div class="tit">
            第十屆-2017秋拍
          </div>
        </div>
        <div class="nav cur">
          <div class="tit">
            第九屆-2017春拍
          </div>
          <div class="sub-nav">
            <div class="sub-navi cur">
              <a class="sub-tit" href=""><span>御養尚品 - 補品及佳釀專場</span></a>
              <a class="download" href=""></a>
            </div>
            <div class="sub-navi">
              <a class="sub-tit" href="#"><span>御養尚品 - 補品及佳釀專場</span></a>
              <a class="download" href=""></a>
            </div>
          </div>
        </div>
        <div class="nav">
          <div class="tit">
            第十屆-2017秋拍
          </div>
        </div> -->
      </div>
      <div class="container container2">
          <?php if(count($notice)>0):?>
            <?php if ($curLang === 'tc'): ?>
              <div class="notice">
                <a href="<?php echo $notice[0]['url_tc']?>"><span><?php echo $notice[0]['content_tc']?></span></a>
              </div>
            <?php else: ?>
              <div class="notice">
                <a href="<?php echo $notice[0]['url_en']?>"><span><?php echo $notice[0]['content_en']?></span></a>
              </div>
            <?php endif; ?>
          <?php endif;?>


        <div class="performance">
          <?php if(count($catalogueParent)>0):?>
            <div class="top">
              <div class="wrap2">
                <div class="tit">
                  <?php if ($curLang === 'tc'): ?>
                    <?php echo $catalogueParent->name_tc; ?>
                  <?php else: ?>
                    <?php echo $catalogueParent->name_en; ?>
                  <?php endif; ?>
                </div>
                <?php if(!empty($catalogueParent->pdf)):?>
                  <div class="pdf">
                      <a target="_blank" href="<?php echo $catalogueParent->pdf; ?>" class="download"></a>
                  </div>
                <?php endif; ?>
              </div>
            </div>
          <?php endif;?>
          <?php if ($curLang === 'tc'): ?>
            <?php foreach ($catalogue['list'] as $k => $v): ?>
              <div class="item">
                <div class="info">
                  <div class="wrap2">
                    <div class="pic">
                      <?php if(strpos($v['pic'],',')): ?>
                        <a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>">
                          <img src="<?php echo strstr($v['pic'], ',', TRUE) ?>" alt="">
                        </a>
                      <?php else: ?>
                        <a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>">
                          <img src="<?php echo $v['pic'] ?>" alt="">
                        </a>
                      <?php endif; ?>
                    </div>
                    <div class="detail">
                      <div class="name"><a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>"><?php echo $v['title_tc']; ?></a></div>
                      <div class="lot">LOT: <span class="no"><?php echo $v['num']; ?></span></div>
                      <div class="estimated">
                        <?php if($v['prize_tc']): ?>
                          成交價（含佣金）：HK$ <span class="money"><?php echo $v['prize_tc']; ?></span>
                        <?php else: ?>
                          估計價格：HK$ <span class="money"><?php echo $v['prize_en']; ?></span>
                        <?php endif; ?>
                      </div>
                      <div class="instruction">
                          查看更多
                        <!-- <?php echo $v['descript_tc']; ?> -->
                      </div>
                    </div>
                    <div class="more">
                      <a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>">Read More</a>
                    </div>
                  </div>
                </div>
              </div>
            <?php endforeach; ?>
          <?php else:?>
            <?php foreach ($catalogue['list'] as $k => $v): ?>
              <div class="item">
                <div class="info">
                  <div class="wrap2">
                    <div class="pic">
                      <?php if(strpos($v['pic'],',')): ?>
                        <a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>">
                          <img src="<?php echo strstr($v['pic'], ',', TRUE) ?>" alt="">
                        </a>
                      <?php else: ?>
                        <a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>">
                          <img src="<?php echo $v['pic'] ?>" alt="">
                        </a>
                      <?php endif; ?>
                    </div>
                    <div class="detail">
                      <div class="name"><a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>"><?php echo $v['title_en']; ?></a></div>
                      <div class="lot">LOT: <span class="no"><?php echo $v['num']; ?></span></div>
                      <div class="estimated">
                        <?php if($v['prize_tc']): ?>
                          PRICE (included premium):HK$ <span class="money"><?php echo $v['prize_tc']; ?></span>
                        <?php else: ?>
                          ESTIMATE PRICE：HK$ <span class="money"><?php echo $v['prize_en']; ?></span>
                        <?php endif; ?>
                      </div>
                      <div class="instruction">
                        <!-- <?php echo $v['descript_tc']; ?> -->
                        read more
                      </div>
                    </div>
                    <div class="more">
                      <a href="<?=$home?>catalogue/detail?id=<?php echo $v['id']?>">Read More</a>
                    </div>
                  </div>
                </div>
              </div>
            <?php endforeach; ?>
          <?php endif;?>
          </div>
          <div id="pagelist">
            <ul>
              <?php echo $this->pagination->create_links();?>
            </ul>
          </div>
        </div>
      </div>


  </div>
<script src="<?php echo $resource_url; ?>js/catalogue.js" charset="utf-8"></script>
